### ISSUE TITLE
ClassTools can't build or can't link

### ISSUE THREAD

**Issue by mcagabe19** [crowplexus/SScript#1]
seems like clang refuses to compile ``ClassTools`` in android it gives Seg Fault and also in [Mac](https://github.com/ShadowMario/FNF-PsychEngine/issues/13484) and [Windows](https://media.discordapp.net/attachments/1142560387519234080/1165264837941657630/image.png?ex=65463872&is=6533c372&hm=d12ffa30c99eacf0128362dd94b8145ab9be2c5dea57e9177c5611f8ad025c74&=&width=1080&height=226) too (linux didn't test) but gcc compiles normally even in 6.1.800

**Comment by TahirKarabekiroglu** [comment]
> seems like clang refuses to compile `ClassTools` in android it gives Seg Fault and also in [Mac](https://github.com/ShadowMario/FNF-PsychEngine/issues/13484) and [Windows](https://media.discordapp.net/attachments/1142560387519234080/1165264837941657630/image.png?ex=65463872&is=6533c372&hm=d12ffa30c99eacf0128362dd94b8145ab9be2c5dea57e9177c5611f8ad025c74&=&width=1080&height=226) too (linux didn't test) but gcc compiles normally even in 6.1.800

SScript is discontinued therefore nothing will be done about bugs and compile errors.

**Comment by mcagabe19** [comment]
> > seems like clang refuses to compile `ClassTools` in android it gives Seg Fault and also in [Mac](https://github.com/ShadowMario/FNF-PsychEngine/issues/13484) and [Windows](https://media.discordapp.net/attachments/1142560387519234080/1165264837941657630/image.png?ex=65463872&is=6533c372&hm=d12ffa30c99eacf0128362dd94b8145ab9be2c5dea57e9177c5611f8ad025c74&=&width=1080&height=226) too (linux didn't test) but gcc compiles normally even in 6.1.800
> 
> SScript is discontinued therefore nothing will be done about bugs and compile errors.

then SScript should be removed from Psych Engine due Mac, iPhone and Android Clang's refuse to build

**Comment by TahirKarabekiroglu** [comment]
> > > seems like clang refuses to compile `ClassTools` in android it gives Seg Fault and also in [Mac](https://github.com/ShadowMario/FNF-PsychEngine/issues/13484) and [Windows](https://media.discordapp.net/attachments/1142560387519234080/1165264837941657630/image.png?ex=65463872&is=6533c372&hm=d12ffa30c99eacf0128362dd94b8145ab9be2c5dea57e9177c5611f8ad025c74&=&width=1080&height=226) too (linux didn't test) but gcc compiles normally even in 6.1.800
> > 
> > 
> > SScript is discontinued therefore nothing will be done about bugs and compile errors.
> 
> then SScript should be removed from Psych Engine due Mac, iPhone and Android Clang's refuse to build (they're not have gcc compilers but android old ndk's has gcc compilers but it's old and sometimes doesn't compile at all)

It will be removed soon
